spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /profile/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${ruoyi.profile}

# 文件上传配置
ruoyi:
  profile: /Users/linjianhai/mycode/Intelligent_service/uploadPath
  # 头像上传路径
  avatar:
    path: /avatar 